post http://localhost:8080/w/rest.php/kzchatbot/v0/question
Content-Type: application/json

{
    "text": "האם מגיע לי לקבל כסף עבור ראש השנה? לא עבדתי אבל הבנתי שכן אמורים לשלם על זה",
    "uuid": "66b5037bb76e1",
    "referrer": 16089
}
